/*
	ODBO provider for XMLA data stores
    Copyright (C) 2014-2015  ARquery LTD
	http://www.arquery.com

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

	@description
					a tabular rowset generated by a MDX query (drillthrough)
*/


#include "stdafx.h"
#include "tabular_rowset.h"
#include "data_source.h"



ATLCOLUMNINFO* tabular_row_data::GetColumnInfo(void* pThis, DBORDINAL* pcCols)
{
	return static_cast< tabular_rowset* >( pThis )->m_execute_response->access_tab_data().GetColumnInfo( pcCols );
}

HRESULT tabular_rowset::Execute(DBPARAMS * /*pParams*/, DBROWCOUNT* pcRowsAffected)
{
	IExtendCommand* pIExtCommand = NULL;
	HRESULT hr = m_spUnkSite->QueryInterface( __uuidof( IExtendCommand ), ( void**) &pIExtCommand );
	
	if FAILED( hr ) return hr;

	pIExtCommand->GetDataHolder( (void**)&m_execute_response );
	pIExtCommand->Release();

	if (nullptr == m_execute_response) { return E_FAIL; }
	execute_response::tabular_data_access& tab_data = m_execute_response->access_tab_data();
	const int row_count = tab_data.row_count();;
	const int data_size = tab_data.data_size();



	if ( (NULL != pcRowsAffected) )
	{
		*pcRowsAffected = row_count-1;
	}

	for ( int i = 1; i < row_count; ++i )
	{
		tabular_row_data crt(data_size);
		tab_data.load_at( i, (wchar_t*)&crt );
		m_rgRowData.Add( crt );
	}



	return S_OK;
}